-- @/sql/partition/01_create_partitioned_examples.sql
-- パーティションを持つテーブルを作成
CREATE TABLE
    APPUSER.PARTITIONED_EXAMPLES (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NAME VARCHAR2(100) NOT NULL,
        CREATED_BY VARCHAR2(50) NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
PARTITION BY
    RANGE (CREATED_AT) (
        PARTITION p2023
        VALUES
            LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
            PARTITION p2024
        VALUES
            LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
            PARTITION pmax
        VALUES
            LESS THAN (MAXVALUE)
    )
;

-- レコードを挿入
INSERT INTO
    APPUSER.PARTITIONED_EXAMPLES (NAME, CREATED_BY, CREATED_AT)
VALUES
    (
        'Alice',
        'admin',
        TO_TIMESTAMP(
            '2023-01-01 00:00:00.000',
            'YYYY-MM-DD HH24:MI:SS.FF3'
        )
    )
;

INSERT INTO
    APPUSER.PARTITIONED_EXAMPLES (NAME, CREATED_BY, CREATED_AT)
VALUES
    (
        'Bob',
        'admin',
        TO_TIMESTAMP(
            '2024-01-01 00:00:00.000',
            'YYYY-MM-DD HH24:MI:SS.FF3'
        )
    )
;

INSERT INTO
    APPUSER.PARTITIONED_EXAMPLES (NAME, CREATED_BY, CREATED_AT)
VALUES
    (
        'Charlie',
        'system',
        TO_TIMESTAMP(
            '2025-01-01 00:00:00.000',
            'YYYY-MM-DD HH24:MI:SS.FF3'
        )
    )
;

-- 確認 (パーティション未指定)
SELECT
    *
FROM
    APPUSER.PARTITIONED_EXAMPLES
;

-- 確認 (パーティション指定)
SELECT
    *
FROM
    APPUSER.PARTITIONED_EXAMPLES PARTITION (p2023)
;

SELECT
    *
FROM
    APPUSER.PARTITIONED_EXAMPLES PARTITION (p2024)
;

SELECT
    *
FROM
    APPUSER.PARTITIONED_EXAMPLES PARTITION (pmax)
;
